apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  type: ClusterIP  # Not LoadBalancer (since Ingress manages external traffic)
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80      # Port the Ingress will use
      targetPort: 8000  # Must match your Django container port