apiVersion: v1
kind: Service
metadata:
  name: django-app-service
spec:
  type: LoadBalancer  # Change from ClusterIP to LoadBalancer
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000